export const dark = {
  bg:        'var(--bg)',
  bgAlt:     'var(--bg-alt)',
  surface:   'var(--surface)',
  surface2:  'var(--surface2)',
  surface3:  'var(--surface3)',
  hover:     'var(--hover)',
  line:      'var(--line)',
  line2:     'var(--line2)',
  line3:     'var(--line3)',
  text:      'var(--text)',
  textSub:   'var(--text-sub)',
  textDim:   'var(--text-dim)',
  textMute:  'var(--text-mute)',
  accent:    'var(--accent)',
  accentDim: 'var(--accent-dim)',
  accentLine:'var(--accent-line)',
  accentBg:  'var(--accent-bg)',
  danger:    'var(--danger)',
  dangerDim: 'var(--danger-dim)',
  success:   'var(--success)',
};
